name: Message for PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  run:
    name: Send a message for PR
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem para PR
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":bell: *Notícias de PR!*",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "${{ github.event.pull_request.title }}",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "fields": [
                    {
                      "title": "Autor",
                      "value": "${{ github.event.pull_request.user.login }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.head_ref }} → ${{ github.base_ref }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
