# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post an inline text message
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Commit message
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem para commit
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":black_nib: *Novo commit*",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "${{ github.event.head_commit.message}}",
                  "fields": [
                    {
                      "title": "Autor",
                      "value": "${{ github.event.pull_request.user.login }}",
                      "short": true
                    },
                  ]
                }
              ]
            }
